apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gzkss1vdj-go 
  janus-idp.io/tekton: gzkss1vdj-go
  backstage.io/kubernetes-id: gzkss1vdj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gzkss1vdj-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  