apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gzkss1vdj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gzkss1vdj-go 
  name: gzkss1vdj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gzkss1vdj-go 
